### ISSUE TITLE
Suggerimenti di miglioramenti

### ISSUE THREAD

**Issue by squintarelli** [SDF-Ingegneria-2022/smoothPoll#112]
complimenti per il lavoro!
perche' non lo pubblicate sotto https://g0v.it ?
c'è un gruppo di lavoro sul MJ che tra l'altro ha sviluppato anche una versione "Clustered" che potreste adottare come backend per segmentare automaticamente i votanti in gruppi (unsupervised learning) e scegliere il candidato con grado maggioritario più elevato in quel gruppo.
questo è stato un paper abbastanza discusso in recenti conferenze su computational social choice e gli autori sono in contatto con lo stesso Balinski

alcuni suggerimenti 
1) nell'elenco nella homepage, per ogni sondaggio, mettete una icone di condivisione che copia il link per votare nella clipboard, in modo che sia facile incollarla in whatsapp/telegram 
2) nella pagina "tutti i sondaggi" http://sceglimeglio.site/gestione-sondaggi/?page=1&per_page=10  mettete la possibilita' di scegliere se vedere tutti i sondaggi, quelli conclusi  e quelli ancora aperti
3) sarebbe bene, quando si crea un sondaggio, di chiedere alla fine un indirizzo email (cui inviare un link di attivazione per mandare "on air" il sondaggio e, in questa mail, dare anche un link che consenta a chi lo ha creato di modificarlo (possibile solo se non e' gia' on air)  il link ovviamente deve avere uns token non indovinabile... 
un ulteriore link nella mail e' quello da distribuire per votare ed un altro ancora per vedere il risultato
4) uno dei parametri nella creazione del sondaggio è "pubblico/privato". se e' pubblico finisce nell'elenco dei sondaggi, se e' privato e' accessibile solo tramite i link della mail di cui sopra.(3)
5) da qualche parte, inserendo il proprio indirizzo email, si riceve una mail con link a tutti i propri sondaggi...

**Comment by Minskal** [comment]
Grazie mille per il messaggio.
Per quanto riguarda i suggerimenti relativi alla pagina dei sondaggi abbiamo in programma di effetturare modifiche utili agli utenti come quelle consigliate.
Riguardo l'utilizzo delle email, stiamo attualmente implementando l'autenticazione degli utenti tramite Google, per limitare anche le operazioni di modifica, cancellazione e creazione di sondaggi solamente ad utenti identificati, mentre utenti anonimi saranno ancora abilitati a votare o visualizzare risultati.
Infine, per la proposta su https://g0v.it/, questo progetto è, almeno per ora, solamente a scopo universitario, pertanto stiamo dando priorità alla conclusione di tutti i punti da noi prefissati. Tuttavia ritengo la proposta molto interessante e ne discuterò con gli altri membri del team.
